In [ ]:
import pandas as pd
import random as randn
import numpy as np


data = pd.Series(np.random.randn(9),
                index=[['a','a','a','b','b','c','c','d','d'],[1,2,3,1,3,1,2,2,3]])
data

a  1   -1.218340
   2    0.143360
   3   -1.005521
b  1   -2.504287
   3    1.089213
c  1   -1.507939
   2   -0.045602
d  2   -1.045364
   3    0.347739
dtype: float64

In [ ]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
data['b']

data['b':'c']

b  1   -2.504287
   3    1.089213
c  1   -1.507939
   2   -0.045602
dtype: float64

In [ ]:
data.loc[['b','d']]

b  1   -2.504287
   3    1.089213
d  2   -1.045364
   3    0.347739
dtype: float64

In [ ]:
data.loc[:, 2]

a    0.143360
c   -0.045602
d   -1.045364
dtype: float64

In [ ]:
data.unstack()

1         2         3
a -1.218340  0.143360 -1.005521
b -2.504287       NaN  1.089213
c -1.507939 -0.045602       NaN
d       NaN -1.045364  0.347739

In [ ]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                     index=[['a', 'a','b','b'],[1,2,1,2,]],
                     columns = [['Ohio','Ohio','Colorado'], ['Green','Red','Green']])

frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [ ]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [ ]:
##컬럼의 부분 집합

frame['Ohio']


color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [ ]:
 ## 계층적 색인에서 계층의 순서를 바꾸거나 지정된 계층에 따라 데이터를 정렬해야 하는 경우가 있을 수 있다.
 
  frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [ ]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [ ]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [ ]:
## 많은 기술 통계와 요약 통계는 level 옵션을 가지고 있는데 어떤 한 축에  대한 합을 구하고 싶은 단계를 지정할 수 있는 옵션이다.

frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [ ]:
#DataFrame에서의 컬럼을 사용하여 인덱싱 

frame = pd.DataFrame({'a': range(7), 'b':range(7,0,-1),
                      'c': ['one','one','one','two','two','two','two'],
                      'd':[0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [ ]:
frame2 = frame.set_index(['c','d'])
frame2

## 데이터 프레임의 set_index 함수는 하나 이상의 컬럼을 색인으로 하는 새로운 데이터 프레임을 생성한다. 


a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [ ]:
#8.2 데이터 합치기 

# 판다스 객체에 저장된 데이터는 여러가지 방법으로 합칠 수 있다
# pandasmerge는 하나 이상의 키를 기준으로 DataFrame의 로우를 합친다. SQL이나 다른 데이터 베이스에서 join과 비슷하다 
#pandas.concat은 하나의 축을 따라 객체를 이어 붙인다.

#combinc_first 인스턴스 매서드는 두 객체를 포개서 한 객체에서 누락된 데이터를 다른 객체에 있는 값으로 채울 수 있도록 한다. 
#이 기법은 책 전체에서 활용된다.



#데이터 베이스 스타일로 DataFrame 합치기

df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1' : range(7)})

df2 = pd.DataFrame({'key': ['a','b','d'],
                    'data2' : range(3)})

df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [ ]:
df2

#잘 살펴보면 c와 d가 빠져있다m erge함수는기본적으로 내부조인을 수행하고

key  data2
0   a      0
1   b      1
2   d      2

In [ ]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
df3 = pd.DataFrame({'lkey':['b','b','a','c','a','a','b'],
                     'data1' : range(7)})

In [ ]:
df4 = pd.DataFrame({'rkey':['a','b','d'],
                    'data2' : range(3)})



In [ ]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [ ]:
#merge 매서드의 종류에 따라서 어떤 키 조합이 결과로 반환되는지
# 알려면 실제 구현과는 조금 다르지만 여러개의 키가 들어있는 튜플의 배열이 단일 조인키로 사용된다고 생각하면 된다.

left = pd.DataFrame({'key1':['foo','foo','bar'],
                     'key2':['one','two','one'],
                     'lval':[1,2,3]})

right = pd.DataFrame({'key1':['foo','foo','bar','bar'],
                      'key2':['one','one','one','two'],
                      'rval':[4,5,6,7]})

pd.merge(left, right, on=['key1','key2'], how='outer')
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [ ]:
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],
                      'value':range(6)})

right1 = pd.DataFrame({'group_val':[3.5, 7]}, index=['a', 'b'])

left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [ ]:
right1

group_val
a        3.5
b        7.0

In [ ]:
pd.merge(left1,right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [ ]:
pd.merge(left1, right1, left_on='key', right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [ ]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [ ]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [ ]:
## Series 나 DataFrame같은 pandas 객체들은 컨텍 내부엔 축마다 이름이 있어서 쉽게 이어붙일 수 있게 되었다

#만약에 연결하려는 두객체의 색인이 서로 다르면 그 결과는 색인의 교집합 또는 합집합? 합쳐진 결과에서 합치기전 객체의 데이터를 구분할 수 있어야 하는가?
#어떤 축으로 연결할 것인지 고려해야 하는가?

#pandas의 concat함수는 위 사항들에 대한 답을 제시한다. doncat함수가 어떻게 동작하는 것인지 예제로 알아보자 

In [ ]:
s1 = pd.Series([0,1], index = ['a','b'])
s2 = pd.Series([2,3,4], index=['c','d','e'])
s3 = pd.Series([5, 6], index=['f','g'])   

In [ ]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [ ]:
pd.concat([s1, s2, s3], axis = 1)


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [ ]:
# 이경우에는 겹치는 부분이 없이 때문에 합집합을 얻었지만 교집합을 얻을 수 있다. 



In [ ]:
#마지막으로 DataFrame의 로우 색인이 분석에 필요한 데이터를 포함하고 있지 않은 경우 어떻게 처리할 것 인가

In [ ]:
#겹치는 데이터 합치기

a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f','e','d','c','b','a'])

b = pd.Series(np.arange(len(a), dtype=np.float64),
              index = ['f','e','d','c','b','a'])
b[-1] = np.nan


np.where(pd.isnull(a), b, a)



array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [ ]:
#데이터 프레임에서 combine_first 메서드는 컬럼에 대해 같은 동작을 수행

In [ ]:
df1 = pd.DataFrame({'a':[1., np.nan, 5., np.nan],
                    'b':[np.nan, 2., np.nan, 6.],
                    'c': range(2,18,4)})

In [ ]:
df2 = pd.DataFrame({'a':[5., 4., np.nan, 3., 7.],
                    'b': [np.nan, 3., 4., 6., 8.]})

In [ ]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [ ]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [ ]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [ ]:
#83 Reshaping andPivoting 표 형식의 데이터를 재배치하느 ㄴ다양한 기본 연산이 존재한다. 이런연산을 재형성 또는 피연산이라고 한다.

#계층적 색인으로 재형성




In [ ]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(['Ohio', 'Colorado'], name='state'),
                    columns=pd.Index(['one','two','three'],
                                     name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [ ]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [ ]:

# 기본적으로 가장 안쪽에 있는 레벨부터 끄집어 내는데 스택도 같다) 레벨 숫자나 이름을 
#전달해서 끄집어낼 단계를 저장할 수 있다 
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [ ]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [ ]:
import pandas as pd 
s1 = pd.Series([0, 1,2 ,3], index = ['a','b','c','d'])

In [ ]:
#데이터베이스나 csv파일에 여러개의 시계열 데이터
#저장하는 일반적인 방법은 시간순서대로 나열하는 것이다. 

data = pd.read_csv('macrodata.csv')
data.head()

year  quarter   realgdp  realcons  ...  unemp      pop  infl  realint
0  1959.0      1.0  2710.349    1707.4  ...    5.8  177.146  0.00     0.00
1  1959.0      2.0  2778.801    1733.7  ...    5.1  177.830  2.34     0.74
2  1959.0      3.0  2775.488    1751.8  ...    5.3  178.657  2.74     1.09
3  1959.0      4.0  2785.204    1753.7  ...    5.6  179.386  0.27     4.06
4  1960.0      1.0  2847.699    1770.5  ...    5.2  180.007  2.31     1.19

[5 rows x 14 columns]

In [ ]:
periods = pd.PeriodIndex(year=data.year, quarter=data.quarter, name='date')

columns = pd.Index(['realgdp','infl','unemp'], name='item')


AttributeError: ignored

In [ ]:
data = data.reindex(columns=columns)


In [ ]:
data.index = periods.to_timestamp('D','end')


In [ ]:
ldata = data.stack().reset_index().rename(columns={0:'value'})
ldata[:10]

date     item     value
0 1959-03-31 23:59:59.999999999  realgdp  2710.349
1 1959-03-31 23:59:59.999999999     infl     0.000
2 1959-03-31 23:59:59.999999999    unemp     5.800
3 1959-06-30 23:59:59.999999999  realgdp  2778.801
4 1959-06-30 23:59:59.999999999     infl     2.340
5 1959-06-30 23:59:59.999999999    unemp     5.100
6 1959-09-30 23:59:59.999999999  realgdp  2775.488
7 1959-09-30 23:59:59.999999999     infl     2.740
8 1959-09-30 23:59:59.999999999    unemp     5.300
9 1959-12-31 23:59:59.999999999  realgdp  2785.204